// LOCALHOST
###
GET http://localhost:8080/contacts

// We use POST when we want  to send a create request 
//we create the info manually
###
POST http://localhost:8080/contacts  HTTP/1.1
content-type: application/json

{
     "firstName": "Russel M.",
    "lastName": "Nelson",
    "email": "nelson3445@gmail.com",
    "favoriteColor": "Blue",
    "birthday": "09/09/1924"
}

// We use PUT when we want  to update the data we have been created 
// we actually change the info manually 
//after we get the Id from the created info, 
//we copy and paste the Id right after the contacts in the url 
###
PUT http://localhost:8080/contacts/640480b848f7ad48a7d194a7  HTTP/1.1
content-type: application/json

{
     "firstName": "SRom",
    "lastName": "Tam",
    "email": "Sr3445@gmail.com",
    "favoriteColor": "Red",
    "birthday": "02/25/14"
}


//we use DELETE when we want to delete the update the info and no need to type the info
// anymore only the Id
//we copy and paste the Id right after the DELETE URL
###
DELETE  http://localhost:8080/contacts/640480b848f7ad48a7d194a7  HTTP/1.1